### ISSUE TITLE
Navi doesn't support backward compatibility

### ISSUE THREAD

**Issue by dbof10** [trello/navi#56]
APIs lower 21 do not have PersistableBundle class, so NaviActivity does not work on those devices.

**Comment by mlatu** [comment]
Use `NaviAppcompatActivity`

**Comment by dlew** [comment]
`NaviActivity` should work pre-21. You just need to avoid using the callbacks with `PersistableBundle` in them.

**Comment by dbof10** [comment]
My Activity just extends from NaviAppCompatActivity. I do not use any callbacks with PersistableBundle. 
It crashes on the line of EventBus.getDefault().register(this). Could you check this out with EventBus?

**Comment by dlew** [comment]
There is no `EventBus` in Navi, so it sounds like the bug is with wherever you're getting that, not Navi.

**Comment by dbof10** [comment]
I created a new project using Navi along with EventBus. I got the tracestack

FATAL EXCEPTION: main
                                                                                 Process: com.example.admin.myapplication, PID: 11689
                                                                                 java.lang.NoClassDefFoundError: android/os/PersistableBundle
                                                                                     at java.lang.Class.getDeclaredMethods(Native Method)
                                                                                     at java.lang.Class.getPublicMethodsRecursive(Class.java:894)
                                                                                     at java.lang.Class.getMethods(Class.java:877)
                                                                                     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157)
                                                                                     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
                                                                                     at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
                                                                                     at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
                                                                                     at com.example.admin.myapplication.MainActivity.onResume(MainActivity.java:39)
                                                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
                                                                                     at android.app.Activity.performResume(Activity.java:5490)
                                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2929)
                                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2968)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2401)
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:149)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
                                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.PersistableBundle" on path: DexPathList[[zip file "/data/app/com.example.admin.myapplication-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.admin.myapplication-1, /vendor/lib, /system/lib, /system/lib/arm]]
                                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                     at java.lang.Class.getDeclaredMethods(Native Method) 
                                                                                     at java.lang.Class.getPublicMethodsRecursive(Class.java:894) 
                                                                                     at java.lang.Class.getMethods(Class.java:877) 
                                                                                     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157) 
                                                                                     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88) 
                                                                                     at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64) 
                                                                                     at org.greenrobot.eventbus.EventBus.register(EventBus.java:136) 
                                                                                     at com.example.admin.myapplication.MainActivity.onResume(MainActivity.java:39) 
                                                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192) 
                                                                                     at android.app.Activity.performResume(Activity.java:5490) 
                                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2929) 
                                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2968) 
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2401) 
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:149) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5257) 
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633) 
                                                                                     at dalvik.system.NativeStart.main(Native Method) 

What at line 39 is EventBus.getDefault().register(this).
The simple app doesn't work on pre-21 but work on 21+. I am not sure this bug related to Navi or EventBus

**Comment by dlew** [comment]
The problem is in EventBus automatically scanning everything without regard for minSdkVersion. I would file an issue with them: https://github.com/greenrobot/EventBus/issues

**Comment by ihorb10** [comment]
Hi @dlew, I got the same error for Android 4.4.2 when I'm using `navi` & `greenrobot` together. For android >= 5.0 everything works.

In [Troubleshooting](http://greenrobot.org/eventbus/documentation/faq/) section for greenrobot lib they propose to not use:
 `onCreate (Bundle savedInstanceState, PersistableBundle persistentState)` in Activity at all. 

So, if I understand correctly there is no solution to use `navi` & `greenrobot` together?

P.S. Thank you for the great library :)

**Comment by dlew** [comment]
I'm not familiar with greenrobot at all, but the linked article has a number of other solutions that indicate that you could use navi and greenrobot together (such as using a subscriber index or attaching to a different subscriber class).

**Comment by ihorb10** [comment]
I have tried `subscriber index`. The problem is that GreenRobot is checking super class too, where `NaviAppCompatActivity` will not be indexed and from [docs](http://greenrobot.org/eventbus/documentation/subscriber-index/)

>When EventBus cannot use an index, it will automatically fallback to reflection at run time.

>attaching to a different subscriber class

I understand that this is possible, but I'm trying to solve this issue. Or will use another EventBus lib

Thank you

**Comment by IgorB10** [comment]
The issue is already created https://github.com/greenrobot/EventBus/issues/351.

Thank you!
